server:
  port: 8081
  context-path: /client2

security:
  oauth2:
    client:
      clientId: portlet2
      clientSecret: portletSecret2
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key